### ISSUE TITLE
problem with Dockerfile

### ISSUE THREAD

**Issue by niekbouman** [michael-emmi/ct-verif-images#1]
Dear Michael,

I am trying to run ctverif via its Docker image.
However, I am getting an error when building the Dockerfile, probably related to the fact that Ubuntu (in the docker image) is installing a too-old version of Ruby. (See error output below.)

Would this be easy to fix?

Kind regards,
Niek
(Eindhoven University of Technology
the Netherlands)

-----
error:

Cloning into 'bam-bam-boogieman'...
Invalid gemspec in [bam-bam-boogieman.gemspec]: RubyGems 2.0 or newer is required to protect against public gem pushes.
ERROR:  Error loading gemspec. Aborting.
ERROR:  Could not find a valid gem 'bam-bam-boogieman-*.gem' (>= 0) in any repository
ERROR:  Possible alternatives: bam-bam-boogieman

**Comment by michael-emmi** [comment]
This has docker build has not been maintained for about two years. It relies on an older version of Bam, and the current version is inconsistent with this build process. On top of that, this build relies on a Docker image for Smack, which has not been updated for about two years.

I would advise installing the latest versions of Smack and Bam directly, rather than using these obsolete versions, and using ct-verif as it is used here: https://github.com/imdea-software/verifying-constant-time/tree/test-automation
